# Estadística Aplicada
## Raúl Flores Robles 
### Segunda Sesión
27 de enero de 2023

In [1]:
7>5

True

In [2]:
7>10

False

In [3]:
7>5 & 7>10

False

In [4]:
7+5

12

In [5]:
10-3

7

In [6]:
5*2

10

In [7]:
10/2

5.0

In [8]:
3**2

9

In [9]:
pow(3,2)

9

In [12]:
alumno1 = ['Juan','Perez',23]

In [13]:
alumno1

['Juan', 'Perez', 23]

In [14]:
type(alumno1)

list

In [16]:
estadistica_g4 = ['Juan','Raul','Jimena','Alejandra']

In [17]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [18]:
estadistica_g4[0]

'Juan'

In [19]:
estadistica_g4[0],estadistica_g4[2]

('Juan', 'Jimena')

In [20]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Jimena']

In [21]:
estadistica_g4[:]

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [22]:
estadistica_g4.append('Jaime')

In [23]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra', 'Jaime']

In [24]:
estadistica_g4.remove('Jimena')

In [25]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime']

In [26]:
len(estadistica_g4)

4

In [28]:
conteo_de_lista = len(estadistica_g4)

In [29]:
conteo_de_lista

4

In [31]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: yfinance in c:\users\lenovo\anaconda3\lib\site-packages (0.2.7)



In [32]:
import yfinance as yf

In [33]:
import numpy as np

In [34]:
numeros = [25.7,8,10]

In [35]:
type(numeros)

list

In [36]:
numeros = np.array(numeros)

In [37]:
type(numeros)

numpy.ndarray

In [38]:
np.sum(numeros)

43.7

In [39]:
np.prod(numeros)

2056.0

In [40]:
np.mean(numeros)

14.566666666666668

In [44]:
np.var(numeros)
#varianza poblacional

62.642222222222216

In [45]:
np.var(numeros,ddof=1)
#varianza muestral

93.96333333333332

In [47]:
np.std(numeros)
#desviacion estandar poblacional

7.9146839622452525

In [49]:
np.std(numeros,ddof=1)
#desviacion estandar muestral

9.693468591445134

In [50]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
np.arange(7,15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [58]:
np.random.randint(0,10,2)

array([9, 1])

In [61]:
np.random.seed(5)
aleatoriosu = np.random.randint(10,30,8)

In [62]:
aleatoriosu

array([13, 24, 25, 16, 26, 19, 18, 14])

In [64]:
aleatoriosu = np.sort(aleatoriosu)

In [65]:
aleatoriosu

array([13, 14, 16, 18, 19, 24, 25, 26])

In [66]:
aleatoriosu[2]

16

In [67]:
aleatoriosu[[2,5]]

array([16, 24])

In [69]:
aleatoriosu = [aleatoriosu > 15]

In [70]:
aleatoriosu

[array([False, False,  True,  True,  True,  True,  True,  True])]